### ISSUE TITLE
Breadcrumbs focus state

### ISSUE THREAD

**Issue by bryanjonker-illinois** [web-illinois/ilw-breadcrumbs#2]
![Breadcrumbs](https://github.com/user-attachments/assets/428b3544-48c0-42ce-bdc0-c9f993a1de0f)

Please change the states to match Courtney's document. 

For focus, you can add the following CSS which will reference the variables set in the ilw-global.css document (we are using "outline" instead of any explicit borders)

```
{
    background-color: var(--ilw-link--focus-background-color);
    color: var(--ilw-link--focus-color);
    outline: var(--ilw-link--focus-outline);
}
```

Variables are:
```
--ilw-link--focus-background-color:var(--il-industrial-lighter-4);
--ilw-link--focus-color:var(--il-blue);
--ilw-link--focus-outline:solid var(--il-blue) 1px;
```

**Comment by nhjohnstone** [comment]
@bryanjonker-illinois I think breadcrumbs is fixed, can you take a look at it in the builder and let me know if not?
